{{ if .Values.global.thanos.enabled }}
{{- if and .Values.bucket.enabled .Values.bucket.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thanos.componentname" (list $ "bucket") }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: bucket
{{ with .Values.bucket.deploymentLabels }}{{ toYaml . | indent 4 }}{{ end }}
spec:
  {{- if .Values.bucket.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.bucket.podDisruptionBudget.minAvailable }}
  {{- end  }}
  {{- if .Values.bucket.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.bucket.podDisruptionBudget.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thanos.name" . }}
      app.kubernetes.io/component: bucket
{{- end }}
{{ end }}
