apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agv
  name: agv
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agv
  template:
    metadata:
      labels:
        app: agv
    spec:
      containers:
      - image: edgehub/mockdevice-agv:v0.24.0-rc1
        name: agv
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: agv
        - name: MOCKDEVICE_PORT
          value: "11111"
