apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-agv-deployment
  name: deviceshifu-agv-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-agv-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-agv-deployment
    spec:
      containers:
      - image: edgehub/deviceshifu-http-http:v0.24.0-rc1
        name: deviceshifu-http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: deviceshifu-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-agv"
        - name: EDGEDEVICE_NAMESPACE
          value: "devices"
      volumes:
      - name: deviceshifu-config
        configMap:
          name: agv-configmap-0.0.1
      serviceAccountName: edgedevice-sa
