oap:
  image:
    repository: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/skywalking-oap-server-utc-8
    tag: 8.5.0-es7
  storageType: elasticsearch7

elasticsearchUser: elastic
elasticsearchPassword: elastic

elasticsearch:
  enabled: false
  config:
    host: elasticsearch-proxy
    port:
      http: 9200

elasticsearchEndpint: http://test.com/gateway/elasticsearch/
