apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plc
  name: plc
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plc
  template:
    metadata:
      labels:
        app: plc
    spec:
      containers:
      - image: edgehub/mockdevice-plc:v0.9.0
        name: plc
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: plc
        - name: MOCKDEVICE_PORT
          value: "11111"
