language: java

jdk:
  - openjdk8

#cache:
#  directories:
#    - "$HOME/.m2"

#before_install:
#  - cp .maven.settings.xml $HOME/.m2/settings.xml

jobs:
  include:
#    - stage: findbugs
#      script:
#        - mvn clean package findbugs:findbugs -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dfindbugs.excludeFilterFile=./app/src/test -f pom-java.xml
    - stage: install
      script:
        - mvn install -Dmaven.javadoc.skip=true -Dcheckstyle.skip=false -Drat.skip=false -f pom-java.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
