apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    koord-app: koord-scheduler
  name: scheduler
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      koord-app: koord-scheduler
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        koord-app: koord-scheduler
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: koord-app
                      operator: In
                      values:
                        - koord-scheduler
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - args:
            - --port=10251
            - --logtostderr=true
            - --authentication-skip-lookup=true
            - --v=4
            - --feature-gates=
            - --config=/config/koord-scheduler.config
          command:
            - /koord-scheduler
          image: scheduler:latest
          imagePullPolicy: Always
          name: scheduler
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: healthz
              port: 10251
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /config
              name: koord-scheduler-config-volume
      restartPolicy: Always
      serviceAccountName: koord-scheduler
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: koord-scheduler-config
                path: koord-scheduler.config
            name: koord-scheduler-config
          name: koord-scheduler-config-volume
