global:
  storageClass: "sreworks-hostpath"

  minio:
    accessKey: 'XmizyTRKhgYTrVkK'
    secretKey: 'Df229gtwZ4bssMzK23VJXq9vrGqpxdHA'

  images:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com/sreworks
    tag: v1.2

  accessMode: ingress

  artifacts:
    mavenImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/maven:3.8.3-adoptopenjdk-11 
    openjdk8Image: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/openjdk8:alpine-jre
    openjdk11Image: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/openjdk:11.0.10-jre
    openjdk11AlpineImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/openjdk11:alpine-jre
    apkRepoDomain: mirrors.tuna.tsinghua.edu.cn
    mavenSettingsXml: https://sreworks.oss-cn-beijing.aliyuncs.com/resource/settings.xml  
    alpineImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/alpine:latest
    nodeImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/node:14.20.0-alpine3.15
    npmRegistryUrl: https://registry.npmmirror.com
    migrateImage: sw-migrate 
    postrunImage: sw-postrun
    pythonPip: http://mirrors.aliyun.com/pypi/simple
    minioClientUrl: https://sreworks.oss-cn-beijing.aliyuncs.com/bin/mc-linux-amd64
    python3Image: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/python:3.9.12-alpine
    bentomlImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/bentoml-model-server:0.13.1-py37

    logstashImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/logstash:7.10.2 
    grafanaImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/grafana:7.5.3
    kibanaImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/kibana:7.10.2 
    elasticsearchImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/elasticsearch:7.10.2-with-plugins
    skywalkingOapImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/skywalking-oap-server-utc-8:8.5.0-es7
    skywalkingUiImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/skywalking-ui:8.5.0
    busyboxImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/busybox:1.30

    vvpRegistry: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror
    vvpAppmanagerImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/vvp-appmanager:2.6.1
    vvpGatewayImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/vvp-gateway:2.6.1
    vvpUiImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/vvp-ui:2.6.1

    metricbeatImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/metricbeat:7.10.2 
    filebeatImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/filebeat:7.10.2
    mysqlImage: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/mysql:8.0.22-debian-10-r44

platformName: SREWorks
platformLogo: /static/publicMedia/sreworks.png

installMode: default

progressCheck: false
debug: false
adminInitPassword: "12345678"

images: {}

build:
  isHome: false
  importFrontend: true
  enable: false
  images: {}

core: 
  init: true
  stageId: prod
  appId: flycore

saas:
  init: true
  stageId: prod
  onlyBase: false
  list:
  - cluster
  - app
  - team
  - dataops
  - system
  - job
  - search
  - healing
  - aiops
  - health
  - ocenter
  - help
  - upload
  - demoapp
  baseList:
  - cluster
  - app
  - team
  - system
  - help
  - upload
  - demoapp 
  dataops:
    dbHost: 'prod-dataops-mysql.sreworks-dataops'
    dbPassword: cb56b5is5e21_c359b42223
    dbUser: root
    dbPort: 3306
    esHost: 'prod-dataops-elasticsearch-master.sreworks-dataops'
    esPort: 9200
    esUser: "elastic"
    esPassword: "sreworkses123."
  grafana:
    password: "sreworks123456"

swcli:
  username: superuser
  password: yJfIYmjAiCL0ondV3kY7e5x6kVTpvC3h
  clientId: superclient
  clientSecret: stLCjCPKbWmki65DsAj2jPoeBLPimpJa

source:
  branch: v1.2
  repo: https://code.aliyun.com/sreworks_public/mirror.git

appmanagerbase:
  enabled: true
  redis:
    password: 'siJEULmQYQ' 
 
appmanager:
  enabled: true

  gateway:
    account_super_client_id: common
    account_super_client_secret: common-9efab2399c7c560b34de477b9aa0a465 
    account_super_id: admin
    account_super_secret_key: test-super-secret-key 

  server:
    jvmXMX: "512m"
    docker:
      enableKaniko: true
      account: sreworks
      password: sreworksDocker123q
      registry: registry.cn-zhangjiakou.aliyuncs.com
      namespace: builds




