apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-controller-config
  namespace: system
data:
  colocation-config: |
    {
      "enable": true
    }
  resource-threshold-config: |
    {
      "clusterStrategy": {
        "enable": true
      }
    }
