name: Publish Feathr to PyPI

on:
  push:
    # For every push against the releases/** branch, usually would happen at release time, Tag example - releases/v0.7.0
    branches:
      - 'releases/**'

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build source and wheel distributions
        run: |
          cd ./feathr_project
          python3 -m pip install --upgrade build twine
          python3 -m build --wheel
          python3 -m build --sdist
          twine check --strict dist/*
      
      
   # Build and upload to PyPI
      - name: "Builds and uploads to PyPI"
        run: |
          cd ./feathr_project
          python3 -m twine upload ./dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}