apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: robotarm
  name: robotarm
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robotarm
  template:
    metadata:
      labels:
        app: robotarm
    spec:
      containers:
      - image: edgehub/mockdevice-robot-arm:v0.24.0-rc1
        name: robotarm
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: robotarm
        - name: MOCKDEVICE_PORT
          value: "11111"
