global:
  storageClass: "alicloud-disk-available"

  minio:
    existingSecret: ""
    accessKey: 'XmizyTRKhgYTrVkK'
    secretKey: 'Df229gtwZ4bssMzK23VJXq9vrGqpxdHA'

minio:
  enabled: true

  service:
    type: ClusterIP
  image:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com
    repository: mirror/minio
    tag: v1.0
  
  persistence:
    size: 20Gi

mysql:
  enabled: true

  primary:
    service:
      type: ClusterIP
    persistence:
      size: 20Gi
    extraFlags: "--max-connect-errors=1000 --max_connections=10000"
    configuration: |-
      [mysqld]
      default_authentication_plugin=mysql_native_password
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/plugin
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=16M
      bind-address=0.0.0.0
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      collation-server=utf8_general_ci
      expire_logs_days=3

      [client]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid


  replication:
    enabled: false

  image:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com
    repository: mirror/mysql
    tag: v1.0

  auth:
    rootPassword: 'bGuwsAWQM6K'


redis:
  enabled: true

  cluster:
    enabled: false

  password: 'siJEULmQYQ'

  master:
    service:
      type: ClusterIP
    disableCommands: 
      - FLUSHDB
    persistence:
      size: 20Gi
    
  image:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com
    repository: mirror/redis
    tag: v1.0
  

zookeeper:
  enabled: true

  image:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com
    repository: mirror/zookeeper
    tag: v1.0
 
  persistence:
    size: 20Gi

ingressNginx:
  enabled: false

kruise:
  enabled: true

kafka:
  enabled: true

  persistence:
    size: 20Gi

  image:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com
    repository: mirror/kafka

  zookeeper:
    enabled: false

  externalZookeeper:
    servers: "sreworks-zookeeper:2181"


openebs:
  enabled: true
  localprovisioner:
    deviceClass:
      enabled: false
    hostpathClass:
      name: sreworks-hostpath



