## Development infrastructure for running and testing the Debezium UI
version: '3'
services:
  dbzui-zookeeper:
    container_name: dbzui-zookeeper
    image: debezium/zookeeper:1.8
    networks:
      - dbzui-network
  dbzui-kafka:
    container_name: dbzui-kafka
    image: debezium/kafka:1.8
    ports:
      - "9092:9092"
    depends_on:
      - dbzui-zookeeper
    environment:
      - ZOOKEEPER_CONNECT=dbzui-zookeeper:2181
    networks:
      - dbzui-network
  dbzui-db-pg:
    container_name: dbzui-db-pg
    image: debezium/example-postgres:1.8
    ports:
      - "65432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dbzui-network
  dbzui-db-mysql:
    container_name: dbzui-db-mysql
    image: debezium/example-mysql:1.8
    ports:
      - "63306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysql
    networks:
      - dbzui-network
  dbzui-db-mongo:
    container_name: dbzui-db-mongo
    image: mongo:3.6
    command: ["mongod", "--replSet", "rs0", "--auth"]
    ports:
      - "37017:27017"
    volumes:
    - ./backend/src/test/resources/initialize-mongo-single.js:/docker-entrypoint-initdb.d/initialize-mongo-single.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    networks:
      - dbzui-network
  dbzui-db-oracle:
    container_name: dbzui-db-oracle
    build:
      context: oracle
    ports:
      - "1521:1521"
    networks:
      - dbzui-network
  mongo-initializer:
    image: mongo:3.6
    networks:
      - dbzui-network
    depends_on:
      - dbzui-db-mongo
    command: bash -c 'sleep 20 && mongo -u admin -p admin --authenticationDatabase admin dbzui-db-mongo:27017/inventory --eval "rs.initiate();"'
  dbzui-db-sqlserver:
    container_name: dbzui-db-sqlserver
    build:
      context: sqlserver
    ports:
     - 1433:1433
    networks:
      - dbzui-network
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
  sqlserver-initializer:
    image: debezium-ui_dbzui-db-sqlserver
    networks:
      - dbzui-network
    depends_on:
      - dbzui-db-sqlserver
    command: bash -c 'sleep 60 && /opt/mssql-tools/bin/sqlcmd -S dbzui-db-sqlserver -U sa -P Password! -i inventory.sql'
  dbzui-connect:
    container_name: dbzui-connect
    build:
      context: connect-oracle-jdbc
    ports:
      - "8083:8083"
    depends_on:
      - dbzui-kafka
      - dbzui-db-pg
      - dbzui-db-oracle
    environment:
      - BOOTSTRAP_SERVERS=dbzui-kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_SCRIPTING=true
      - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension
    networks:
      - dbzui-network
  dbzui-backend:
    container_name: dbzui-backend
    build:
      context: .
      dockerfile: Dockerfile.oracle
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://dbzui-connect:8083
    depends_on:
      - dbzui-connect
    networks:
      - dbzui-network
networks:
  dbzui-network:
    external: false
