
{{- if hasPrefix "http://NODE_IP:" .Values.appmanager.home.url -}}
{{ fail "Please replace the NODE_IP value to real node ip in appmanager.home.url" }}
{{- end -}}

{{- if eq .Values.installMode "default" -}}

apiVersion: v1
data:

  IMAGE_PUSH_REGISTRY: {{ .Values.appmanager.server.docker.registry }}/{{ .Values.appmanager.server.docker.namespace }}
  

  APK_REPO_DOMAIN: {{ .Values.global.artifacts.apkRepoDomain }} 
  MAVEN_IMAGE: {{ .Values.global.artifacts.mavenImage }}
  JRE8_IMAGE: {{ .Values.global.artifacts.openjdk8Image }}
  JRE11_IMAGE: {{ .Values.global.artifacts.openjdk11Image }}
  MAVEN_SETTINGS_XML: {{ .Values.global.artifacts.mavenSettingsXml }}
  NODE_IMAGE: {{ .Values.global.artifacts.nodeImage }}
  ALPINE_IMAGE: {{ .Values.global.artifacts.alpineImage }}
  MIGRATE_IMAGE: {{ template "migrate.image" . }}
  POSTRUN_IMAGE: {{ template "postrun.image" . }}
  NPM_REGISTRY_URL: {{ .Values.global.artifacts.npmRegistryUrl }}
  JRE11_ALPINE_IMAGE: {{ .Values.global.artifacts.openjdk11AlpineImage }}
  PYTHON_PIP: {{ .Values.global.artifacts.pythonPip }}
  PYTHON_PIP_DOMAIN: {{ template "python.pip.domain" . }}
  MINIO_CLIENT_URL: {{ .Values.global.artifacts.minioClientUrl }}
  PYTHON3_IMAGE: {{ .Values.global.artifacts.python3Image }}
  BENTOML_IMAGE: {{ .Values.global.artifacts.bentomlImage }}

  LOGSTASH_IMAGE: {{ (split ":" .Values.global.artifacts.logstashImage)._0 | quote }}
  LOGSTASH_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.logstashImage)._1 | quote }}
  GRAFANA_IMAGE: {{ (split ":" .Values.global.artifacts.grafanaImage)._0 | quote }}
  GRAFANA_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.grafanaImage)._1 | quote }}
  KIBANA_IMAGE: {{ (split ":" .Values.global.artifacts.kibanaImage)._0 | quote }}
  KIBANA_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.kibanaImage)._1 | quote }}
  ELASTICSEARCH_IMAGE: {{ (split ":" .Values.global.artifacts.elasticsearchImage)._0 | quote }}
  ELASTICSEARCH_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.elasticsearchImage)._1 | quote }}
  ELASTICSEARCH_IMAGE: {{ (split ":" .Values.global.artifacts.elasticsearchImage)._0 | quote }}
  ELASTICSEARCH_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.elasticsearchImage)._1 | quote }}
  SKYWALKING_OAP_IMAGE: {{ (split ":" .Values.global.artifacts.skywalkingOapImage)._0 | quote }}
  SKYWALKING_OAP_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.skywalkingOapImage)._1 | quote }}
  SKYWALKING_UI_IMAGE: {{ (split ":" .Values.global.artifacts.skywalkingUiImage)._0 | quote }}
  SKYWALKING_UI_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.skywalkingUiImage)._1 | quote }}
  BUSYBOX_IMAGE: {{ (split ":" .Values.global.artifacts.busyboxImage)._0 | quote }}
  BUSYBOX_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.busyboxImage)._1 | quote }}
  
  VVP_REPO:  {{ .Values.global.artifacts.vvpRegistry | quote }}
  VVP_APPMANAGER_REPO:  {{ (split "/" (split ":" .Values.global.artifacts.vvpAppmanagerImage)._0)._2 | quote }}
  VVP_APPMANAGER_IMAGE_TAG:  {{ (split ":" .Values.global.artifacts.vvpAppmanagerImage)._1 | quote }}
  VVP_UI_REPO:  {{ (split "/" (split ":" .Values.global.artifacts.vvpUiImage)._0)._2 | quote }}
  VVP_UI_IMAGE_TAG:  {{ (split ":" .Values.global.artifacts.vvpUiImage)._1 | quote }}
  VVP_GATEWAY_REPO:  {{ (split "/" (split ":" .Values.global.artifacts.vvpGatewayImage)._0)._2 | quote }}
  VVP_GATEWAY_IMAGE_TAG:  {{ (split ":" .Values.global.artifacts.vvpGatewayImage)._1 | quote }}
  METRICBEAT_IMAGE: {{ (split ":" .Values.global.artifacts.metricbeatImage)._0 | quote}}
  METRICBEAT_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.metricbeatImage)._1 | quote }}
  FILEBEAT_IMAGE: {{ (split ":" .Values.global.artifacts.filebeatImage)._0 | quote }}
  FILEBEAT_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.filebeatImage)._1 | quote }}
  MYSQL_REGISTRY: {{ (split "/" .Values.global.artifacts.mysqlImage)._0 | quote }}
  MYSQL_REPO: {{ (split ":" (splitn "/" 2 .Values.global.artifacts.mysqlImage)._1)._0 | quote }}
  MYSQL_IMAGE_TAG: {{ (split ":" .Values.global.artifacts.mysqlImage)._1 | quote }}

  SOURCE_BRANCH: {{ .Values.source.branch | default "master" | quote }}
  SOURCE_REPO: {{ .Values.source.repo }}
  SOURCE_CI_ACCOUNT: {{ .Values.source.ciAccount | default "" | quote }}
  SOURCE_CI_TOKEN: {{ .Values.source.ciToken | default "" | quote }}

  ZOOKEEPER_ENDPOINT: {{ .Release.Name }}-zookeeper
  ENDPOINT_PAAS_MINIO: {{ template "minio.endpoint" . }}
  APPMANAGER_ENDPOINT: {{ .Release.Name }}-appmanager
  KAFKA_ENDPOINT: {{ .Release.Name }}-kafka.{{ .Release.Namespace }}
  AUTHPROXY_ENDPOINT: {{ .Values.core.stageId }}-{{ .Values.core.appId }}-paas-authproxy
  REDIS_ENDPOINT: {{ .Release.Name }}-redis-master.{{ .Release.Namespace }}
  REDIS_PASSWORD: {{ .Values.appmanagerbase.redis.password | quote }}

  APPMANAGER_USERNAME: {{ .Values.swcli.username }}
  APPMANAGER_PASSWORD: {{ .Values.swcli.password }}
  APPMANAGER_CLIENT_ID: {{ .Values.swcli.clientId }}
  APPMANAGER_CLIENT_SECRET: {{ .Values.swcli.clientSecret }}

  MINIO_ACCESS_KEY: {{ .Values.global.minio.accessKey }}
  MINIO_SECRET_KEY: {{ .Values.global.minio.secretKey }}
  GLOBAL_STORAGE_CLASS: {{ .Values.global.storageClass | default "alicloud-disk-available" | quote }}

  ACCESS_MODE: {{ .Values.global.accessMode }}
  NODE_PORT: {{ template "nodePort" . }} 
  #APPMANAGER_SERVICE: {{ .Release.Name }}-appmanager
  CORE_STAGE_ID: {{ .Values.core.stageId }}
  CORE_APP_ID: {{ .Values.core.appId }}

  SAAS_STAGE_ID: {{ .Values.saas.stageId }}
  
  PLATFORM_NAME: {{ .Values.platformName }}
  PLATFORM_LOGO: {{ .Values.platformLogo }}

  NAMESPACE_DATAOPS: {{ template "dataops.namespace" . }} 
  NAMESPACE_AIOPS: {{ template "aiops.namespace" . }} 

  IMPORT_FRONTEND: {{ .Values.build.importFrontend | quote }}
  IMAGE_BUILD_ENABLE: {{ .Values.build.enable | quote }}

  DATAOPS_DB_HOST: {{ .Values.saas.dataops.dbHost | quote }}
  DATAOPS_DB_PASSWORD: {{ .Values.saas.dataops.dbPassword | quote }}
  DATAOPS_DB_PORT: {{ .Values.saas.dataops.dbPort | quote }}
  DATAOPS_DB_USER: {{ .Values.saas.dataops.dbUser | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.saas.grafana.password | quote }} 
  DATA_ES_HOST: {{ .Values.saas.dataops.esHost | quote }}
  DATA_ES_PORT: {{ .Values.saas.dataops.esPort | quote }}
  DATA_ES_USER: {{ .Values.saas.dataops.esUser | quote }}
  DATA_ES_PASSWORD: {{ .Values.saas.dataops.esPassword | quote }}

  DATA_PROM_HOST: "localhost"
  DATA_PROM_PORT: "80"

  ACCOUNT_SUPER_CLIENT_ID: {{ .Values.appmanager.gateway.account_super_client_id }}
  ACCOUNT_SUPER_CLIENT_SECRET: {{ .Values.appmanager.gateway.account_super_client_secret }}
  ACCOUNT_SUPER_ID: {{ .Values.appmanager.gateway.account_super_id }}
  ACCOUNT_SUPER_SECRET_KEY: {{ .Values.appmanager.gateway.account_super_secret_key }}

  HOME_BUILD: {{ .Values.build.isHome | quote }}
  ONLY_BASE: {{ .Values.saas.onlyBase | quote }}

  ADMIN_INIT_PASSWORD: {{ .Values.adminInitPassword | quote }}

kind: ConfigMap
metadata:
  name: init-configmap

{{- end -}}
