apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockdevice-socket
  namespace: devices
spec:
  selector:
    matchLabels:
      app: mockdevice-socket
  template:
    metadata:
      labels:
        app: mockdevice-socket
    spec:
      containers:
      - name: mockdevice-socket
        image: edgehub/mockdevice-socket:v0.24.0-rc1
        ports:
        - containerPort: 11122
