version: "2.2"
services:
  flink-master:
    image: ${FLINK_DOCKER_IMAGE_NAME:-fraud-job:latest}
    ports:
      - "8081:8081"
    command: job-cluster --job-classname com.platform.field.dynamicrules.Main -Djobmanager.rpc.address=flink-master -Dparallelism.default=2 --data-source kafka --rules-source kafka --alerts-sink kafka --rules-export-sink kafka --latency-sink kafka --kafka-host kafka1 --kafka-port 9092

  flink-task-manager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-fraud-job:latest}
    command: task-manager -Djobmanager.rpc.address=flink-master
    scale: ${DEFAULT_PARALLELISM:-2}
