apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plate-reader
  name: plate-reader
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plate-reader
  template:
    metadata:
      labels:
        app: plate-reader
    spec:
      containers:
      - image: edgehub/mockdevice-plate-reader:v0.9.0
        name: plate-reader
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: plate-reader
        - name: MOCKDEVICE_PORT
          value: "11111"
