site_name: CloudEon Documentation
site_description: 构建于kubernetes集群之上的大数据集群管理平台
site_url: https://github.com/dromara/CloudEon
site_author: Pandas886
repo_name: dromara/CloudEon
repo_url: https://github.com/dromara/CloudEon
edit_uri: ""
extra:
  generator: false
  homepage: https://cloudeon.top
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://github.com/Pandas886
    - icon: fontawesome/brands/github
      link: https://github.com/Pandas886

copyright: Copyright &copy; 2023 CloudEon
theme:
  custom_dir: overrides
  name: material
  language: zh
  logo: images/logo.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: deep orange
    accent: deep orange
    # - scheme: slate
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - scheme: default
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
        
  features:
    - navigation.instant
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link
    - navigation.top
#    - navigation.tabs
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest


nav:
  - index.md
  - mind.md
  - 安装部署:
      - 安装部署/install_pre.md
      - 安装部署/docker.md
      - 安装部署/local.md
  - quickstart.md
  - 支持组件:
      - 支持组件/supportservice.md
      - 支持组件/HDFSonK8s.md
      - 支持组件/DorisonK8s.md
      - 支持组件/ZookeeperOnK8s.md
      - 支持组件/KafkaOnK8s.md
      - 支持组件/HbaseOnK8s.md
  - 社区贡献:
      - 社区贡献/communicate.md
      - 社区贡献/contribute.md
      - 社区贡献/develop.md
  - FAQ.md
  - Roadmap.md
