apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thermometer
  name: thermometer
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thermometer
  template:
    metadata:
      labels:
        app: thermometer
    spec:
      containers:
      - image: edgehub/mockdevice-thermometer:v0.9.0
        name: thermometer
        ports:
        - containerPort: 11111
        env:
        - name: MOCKDEVICE_NAME
          value: thermometer
        - name: MOCKDEVICE_PORT
          value: "11111"
