## See https://pre-commit.com for more information
## See https://pre-commit.com/hooks.html for more hooks
files: ^soda/
exclude: antlr/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: soda/scientific/tests/assets/
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        name: Sort imports using isort
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: Run black formatter
        language_version: python3

    #
    # This is a very useful one, but we need to update dependencies first.
    # - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    #   rev: v1.0.5
    #   hooks:
    #     - id: python-bandit-vulnerability-check
    #
    # Too opinionated and iin conflict with black, consider using some parts if possible
    # - repo: https://github.com/pycqa/flake8
    #   rev: 4.0.1
    #   hooks:
    #     - id: flake8
    #       name: Run flake8 linter
    #       additional_dependencies:
    #         ["flake8-bugbear==22.1.11", "pep8-naming==0.12.1"]
    #       args: ["--exclude", "core/sodasqlv3/scan/yaml/parser/*.py"]
    #
    # Many issues reported by mypy, consider iterating towards that standard and enable
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v0.931
    #   hooks:
    #     - id: mypy
    #       name: mypy-core
    #       # exclude: (packages/|core/sodasqlv3/scan/yaml/parser/.*\.py) # See CONTRIBUTING.md on MyPy
