[version]
current = "3.0.26"

regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)((?P<prerelease>[a-z]+)(?P<build>\d+))?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "soda/bigquery/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/core/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/core/soda/__version__.py"
search = 'SODA_CORE_VERSION = "{current_version}"'

[[file]]
src = "soda/postgres/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/redshift/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/snowflake/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/athena/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/spark/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/spark_df/setup.py"
search = 'package_version = "{current_version}"'


[[file]]
src = "soda/db2/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/scientific/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/sqlserver/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/mysql/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/trino/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/dbt/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/dremio/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/oracle/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/duckdb/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/denodo/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/dask/setup.py"
search = 'package_version = "{current_version}"'

[[file]]
src = "soda/vertica/setup.py"
search = 'package_version = "{current_version}"'
