version: '3'
services:
  ranger-tagsync:
    build:
      context: .
      dockerfile: Dockerfile.ranger-tagsync
      args:
        - RANGER_VERSION=${RANGER_VERSION}
    image: ranger-tagsync
    container_name: ranger-tagsync
    hostname: ranger-tagsync.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    depends_on:
      ranger:
        condition: service_started
    environment:
      - RANGER_VERSION

networks:
  ranger:
    name: rangernw
