version: '3'
services:
  ranger:
    build:
      context: .
      dockerfile: Dockerfile.ranger
      args:
        - RANGER_VERSION=${RANGER_VERSION}
        - RANGER_DB_TYPE=${RANGER_DB_TYPE}
    image: ranger:latest
    container_name: ranger
    hostname: ranger.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6080:6080"
    depends_on:
      ranger-zk:
        condition: service_started
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
    environment:
      - RANGER_VERSION
      - RANGER_DB_TYPE
    command:
      - /home/ranger/scripts/ranger.sh

  ranger-zk:
    build:
      context: .
      dockerfile: Dockerfile.ranger-zk
    image: ranger-zk
    container_name: ranger-zk
    hostname: ranger-zk.example.com
    networks:
      - ranger
    ports:
      - "2181:2181"

  ranger-solr:
    build:
      context: .
      dockerfile: Dockerfile.ranger-solr
    image: ranger-solr
    container_name: ranger-solr
    hostname: ranger-solr.example.com
    networks:
      - ranger
    ports:
      - "8983:8983"
    command:
      - solr-precreate
      - ranger_audits
      - /opt/solr/server/solr/configsets/ranger_audits/

networks:
  ranger:
    name: rangernw
