spring:
  profiles:
    include: common-dev
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证中心
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: authFallback
                fallbackUri: forward:/fallback
        # 系统基础设置中心
        - id: service-system
          uri: lb://service-system
          predicates:
            - Path=/system/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: Hystrix
              args:
                name: systemHystrix
                fallbackUri: forward:/fallback
        # 邮件中心
        - id: service-email
          uri: lb://service-email
          predicates:
            - Path=/email/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: Hystrix
              args:
                name: emailHystrix
                fallbackUri: forward:/fallback
        # 文件中心
        - id: service-file
          uri: lb://service-file
          predicates:
            - Path=/file/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fileHystrix
                fallbackUri: forward:/fallback
        # 元数据管理
        - id: service-data-metadata
          uri: lb://service-data-metadata
          predicates:
            - Path=/data/metadata/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataMetadataHystrix
                fallbackUri: forward:/fallback
        # 数据SQL工作台
        - id: service-data-console
          uri: lb://service-data-console
          predicates:
            - Path=/data/console/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataSqlConsoleHystrix
                fallbackUri: forward:/fallback
        # 数据集市中心
        - id: service-data-market
          uri: lb://service-data-market
          predicates:
            - Path=/data/market/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataMarketHystrix
                fallbackUri: forward:/fallback
        # 数据API注册
        - id: service-data-mapping
          uri: lb://service-data-mapping
          predicates:
            - Path=/data/api/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataApiMappingHystrix
                fallbackUri: forward:/fallback
        # 数据服务集成
        - id: service-data-integration
          uri: lb://service-data-integration
          predicates:
            - Path=/data/service/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataIntegrationHystrix
                fallbackUri: forward:/fallback
        # 数据可视化
        - id: service-data-visual
          uri: lb://service-data-visual
          predicates:
            - Path=/data/visual/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataVisualHystrix
                fallbackUri: forward:/fallback
        # 主数据
        - id: service-data-masterdata
          uri: lb://service-data-masterdata
          predicates:
            - Path=/data/masterdata/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataMasterdataHystrix
                fallbackUri: forward:/fallback
        # 数据质量
        - id: service-data-quality
          uri: lb://service-data-quality
          predicates:
            - Path=/data/quality/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataQualityHystrix
                fallbackUri: forward:/fallback
        # 数据标准
        - id: service-data-standard
          uri: lb://service-data-standard
          predicates:
            - Path=/data/standard/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataStandardHystrix
                fallbackUri: forward:/fallback
        # 数据标准
        - id: service-data-system
          uri: lb://service-data-system
          predicates:
            - Path=/data/system/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=2
            - name: Hystrix
              args:
                name: dataSystemHystrix
                fallbackUri: forward:/fallback
        # 定时任务
        - id: service-quartz
          uri: lb://service-quartz
          predicates:
            - Path=/quartz/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: Hystrix
              args:
                name: quartzHystrix
                fallbackUri: forward:/fallback
        # 代码生成器
        - id: service-codegen
          uri: lb://service-codegen
          predicates:
            - Path=/codegen/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: Hystrix
              args:
                name: codegenHystrix
                fallbackUri: forward:/fallback
        # 工作流
        - id: service-workflow
          uri: lb://service-workflow
          predicates:
            - Path=/workflow/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1
            - name: Hystrix
              args:
                name: workflowHystrix
                fallbackUri: forward:/fallback