apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-robotarm-deployment
  name: deviceshifu-robotarm-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-robotarm-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-robotarm-deployment
    spec:
      containers:
      - image: edgehub/deviceshifu-http-http:v0.9.0
        name: deviceshifu-http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: deviceshifu-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-robotarm"
        - name: EDGEDEVICE_NAMESPACE
          value: "devices"
      volumes:
      - name: deviceshifu-config
        configMap:
          name: robotarm-configmap-0.0.1
      serviceAccountName: edgedevice-sa
