#ng_tis_git_src: "https://github.com/qlangtech/ng-tis.git"
ng_tis_git_src: "git@github.com:qlangtech/ng-tis.git"
ng_tis_src_dir: "{{src_root}}/{{ng_tis_app_name}}"
ng_tis_git_branch: "master"

name_ng_tis_node_modules_tar: "tis-console-ng-node-modules.tar.gz"

node_ver: v16.13.0
node_distro: linux-x64
node_name: "node-{{node_ver}}-{{node_distro}}"


node_assemble_tar: "node-v16.13.0-linux-x64.tar.xz"

nodejs_dir: "/usr/local/lib/nodejs"
