
### server config
server:
  port: 7001

### management config
management:
  server:
    port: 7002
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,admin,view


ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 300000
  ServerListRefreshInterval: 20000



### spring application config
spring:
  application:
    name: tesla-gateway
  cloud:
    ### 网关配置
    gateway:
      httpclient:
        response-timeout: 300s
        connect-timeout: 6000 # 连接超时时间6s
        pool:
          type: disabled
          name: gateway-connection-pool
      discovery:
        locator:
          enabled: false # 如果开启，将自动将服务注册上的所有服务都可以通过网关访问

    nacos: # nacos 配置
      discovery:
        namespace: ad2d92c6-1a21-47ac-9da8-203fcbed9146
        server-addr: nacos-daily.tesla.alibaba-inc.com:80
        watch-delay: 30000 #30s
        enabled: true
      config:
        server-addr: nacos-daily.tesla.alibaba-inc.com:80
        namespace: ad2d92c6-1a21-47ac-9da8-203fcbed9146

  redis:
    database: 1
    host: rm-tattesla-common-daily.redis.rdstest.tbsite.net
    password: TeslaAdmin123456
    port: 6379
    timeout: 15000
  resources:
    add-mappings: false



  eagleeye:
    enabled: false

### tesla config
tesla:
  env: prod
  region: private
  auto-online: true #手动去触发上线，避免刚开始启动时，路由未完全初始化，出现No handler
  config:
    gateway:
      admin-token: af82d2e7-a8ec-48ac-8c1c-b6048cd8c64a
      auth-address: http://authproxy-daily.tesla.alibaba-inc.com
      authCookieKey: 0d260eab-4760-4bcd-a0a3-6db6b7a3053e
      authCookieName: userinfo
      jwt-secret: 5e6b47fa-f905-4d1f-b1a9-3d8e06065426
      tesla-auth-app: teslaweb
      tesla-auth-key: b2cbbe79-b832-4b79-aabc-6471c1842e32
      store-nacos-data-id: test_test_test
      store-nacos-group: DEFAULT_GROUP
      store-nacos-namespace: ad2d92c6-1a21-47ac-9da8-203fcbed9146
      store-nacos-addr: nacos-daily.tesla.alibaba-inc.com:80
      enable-doc: false
      reload-config: false




### log config, 开启debug方便排查问题
#logging:
#  level:
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
#    reactor.ipc.netty: debug


