apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockdevice-opcua
  namespace: devices
spec:
  selector:
    matchLabels:
      app: mockdevice-opcua
  template:
    metadata:
      labels:
        app: mockdevice-opcua
    spec:
      containers:
      - name: mockdevice-opcua
        image: edgehub/mockdevice-opcua:v0.9.0
        ports:
        - containerPort: 4840
        readinessProbe:
          tcpSocket:
            port: 4840
          initialDelaySeconds: 3
          periodSeconds: 3
