{{/*This method of configuration is deprecated*/}}
{{- if .Values.kubecostProductConfigs }}
{{- if .Values.kubecostProductConfigs.azureStorageCreateSecret }}
{{- if .Values.kubecostProductConfigs.azureStorageAccessKey }}
{{- if .Values.kubecostProductConfigs.azureStorageAccount }}
{{- if .Values.kubecostProductConfigs.azureStorageContainer }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-config
type: Opaque
stringData:
  azure-storage-config.json: |-
    {
    	"azureStorageAccount": "{{ .Values.kubecostProductConfigs.azureStorageAccount }}",
    	"azureStorageAccessKey": "{{ .Values.kubecostProductConfigs.azureStorageAccessKey }}",
    	"azureStorageContainer": "{{ .Values.kubecostProductConfigs.azureStorageContainer }}"
    }
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}