{{- if .Values.kubecostProductConfigs }}
{{- if .Values.kubecostProductConfigs.clusters }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecost-clusters
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  default-clusters.yaml: |
{{- toYaml .Values.kubecostProductConfigs.clusters | nindent 4 }}
{{- end }}
{{- end }}
