apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "harbor.jobservice" . }}-env"
  labels:
{{ include "harbor.labels" . | indent 4 }}
data:
  CORE_URL: "{{ template "harbor.coreURL" . }}"
  TOKEN_SERVICE_URL: "{{ template "harbor.tokenServiceURL" . }}"
  REGISTRY_URL: "{{ template "harbor.registryURL" . }}"
  REGISTRY_CONTROLLER_URL: "{{ template "harbor.registryControllerURL" . }}"
  REGISTRY_CREDENTIAL_USERNAME: "{{ .Values.registry.credentials.username }}"
  {{- if has "jobservice" .Values.proxy.components }}
  HTTP_PROXY: "{{ .Values.proxy.httpProxy }}"
  HTTPS_PROXY: "{{ .Values.proxy.httpsProxy }}"
  NO_PROXY: "{{ template "harbor.noProxy" . }}"
  {{- end }}
  {{- if .Values.metrics.enabled}}
  METRIC_NAMESPACE: harbor
  METRIC_SUBSYSTEM: jobservice
  {{- end }}
