{{- if eq .Values.installMode "default" -}}

apiVersion: v1
data:
  core.sh: |

    set -e
    set -x
    sleep 999999999   

  saas-cluster.sh: |
    

    set -e
    set -x
  
    envsubst < /root/saas/cluster/api/build.yaml.tpl > /root/saas/cluster/api/build.yaml
    touch /root/saas/cluster/build.yaml
    echo "" > /root/saas/cluster/build.yaml
    cat /root/saas/cluster/ui/build.yaml >> /root/saas/cluster/build.yaml
    echo "---" >>  /root/saas/cluster/build.yaml
    cat /root/saas/cluster/api/build.yaml >> /root/saas/cluster/build.yaml
    cd /root/saas/cluster/
    res=$(/root/swcli --config /swcli/swcli.yaml app-package build --app-id=cluster --tags="release=sreworks/x86_64" -j -d)
 
    package_name=$(echo $res | python -c 'import sys;import json;print(json.loads(sys.stdin.read())["packageVersion"])')
    /root/mc alias set sw http://${ENDPOINT_PAAS_MINIO} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}

    /root/mc share download sw/abm-oxs-appmanager-daily/apps/cluster/${package_name}.zip|grep 'Share'|awk '{print $2}'


  saas-app.sh: |

    set -e
    set -x
    
    sleep 999999999   


  saas-system.sh: |

    set -e
    set -x
    
    sleep 999999999   

  reduce.py: |
    import sys
    import yaml
    import json

    def merge(a, b):
        if b is None:
            return a
        if a is None:
            return b
        parameterValues = [x["name"] for x in a.get("spec").get("parameterValues")]
        for p in b.get("spec").get("parameterValues"):
            if p["name"] in parameterValues: continue
            if p["name"] == "COMPONENT_NAME": continue
            a["spec"]["parameterValues"].append(p)
        a["spec"]["components"] += b["spec"]["components"]
        return a

    res = reduce(merge, [yaml.safe_load(raw) for raw in sys.stdin.read().strip().split("---")])
    print(yaml.dump(res))
 
  saas-dataops.sh: |
    set -e
    set -x 
  
    sleep 9999999999999999  

  saas-team.sh: |

    set -e
    set -x

    sleep 9999999999999    

  saas-aiops.sh: |

    set -e
    set -x

    sleep 9999999999999    



  saas-job.sh: |

    set -e
    set -x

    sleep 9999999999999    


  saas-healing.sh: |

    set -e
    set -x

    sleep 9999999999999    



  saas-health.sh: |

    set -e
    set -x

    sleep 9999999999999    


  saas-ocenter.sh: |

    set -e
    set -x

    sleep 9999999999999    

  saas-help.sh: |

    set -e
    set -x

    sleep 9999999999999    


  saas-search.sh: |

    set -e
    set -x

    sleep 9999999999999    


  saas-sleep.sh: |
    sleep 999999999999

kind: ConfigMap
metadata:
  name: init-build

{{- end -}}
