{{ if .Values.global.thanos.enabled }}
{{ if .Values.compact.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.componentname" (list $ "compact") }}
  {{- with .Values.compact.http.service.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: compact
{{ with .Values.compact.http.service.labels }}{{ toYaml . | indent 4 }}{{ end }}
spec:
  ports:
  - port: {{ .Values.compact.http.port }}
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: compact
{{ with .Values.compact.http.service.matchLabels }}{{ toYaml . | indent 4 }}{{ end }}
{{ end}}
{{ end }}
