---
# tasks file for assemble
#  - file:
#     path: /opt/data/spring-boot
#     owner: "{{tis_user}}"
#     state: directory

  - file:
     path: '{{tis_data_dir}}/flume'
     owner: "{{tis_user}}"
     state: directory

  - name: copy tis-assemble 
    copy:
     src: "{{tis_release_dir}}/{{tis_release_dir_name}}/{{item}}"
     dest: /tmp/
    with_items:
     - "tis-assemble.tar.gz"

#  - name: copy assemble.properties
#    copy:
#     src: "./files/assemble.properties"
#     dest: /opt/data/spring-boot/
#     force: no
  - name: delete history tar.gz
    file:
      path: /tmp/tis-assemble
      state: absent

  - name: untar
    unarchive:
      src: /tmp/tis-assemble.tar.gz
      dest: /tmp/
      remote_src: yes


  - name: synchroniz assemble
    synchronize:
       src: /tmp/tis-assemble/
       dest: "{{app_dir}}/tis-assemble"
       delete: yes
       recursive: yes
    delegate_to: "{{ inventory_hostname }}"
    notify: restart assemble

  - name: mkdir tis-web-config
    file:
     path: "{{app_dir}}/tis-assemble/conf/tis-web-config"
     state: directory

#  - name: copy hdfs-site-proxy.xml
#    template:
#     src: template/hdfs-site-proxy.xml.j2
#     dest: "{{app_dir}}/tis-assemble/conf/tis-web-config/hdfs-site.xml"

  - name: copy flume.properties
    template:
      src: '{{item}}.j2'
      dest: "{{app_dir}}/tis-assemble/conf/{{item}}"
    with_items:
      - "flume.properties"
    notify: restart assemble

  - name: copy config.properties
    template:
     src: 'template/{{item}}.j2'
     dest: "{{app_dir}}/tis-assemble/conf/tis-web-config/{{item}}"
    with_items:
     - "config.properties"
   #  - "yarn-site.xml"
    notify: restart assemble

  - name: path owner set
    file:
     path: "{{item}}"
     owner: "{{tis_user}}"
     recurse: yes
    with_items:
     - "{{app_dir}}/tis-assemble"
     - "/opt/data/spring-boot"