---
- name: Download tis plugins to {{ tis_release_dir }}/{{tis_plugin_release_dir_name}}
  get_url:
    url: "{{ release_repository }}/{{tis_pkg_version}}/{{tis_plugin_release_dir_name}}/{{ item.name }}"
    dest: "{{ tis_release_dir }}/{{tis_plugin_release_dir_name}}/{{tis_pkg_version}}/{{ item.name }}"
    #If yes and dest is not a directory, will download the file every time and replace the file if the contents change
    force: no
  when: item.when
  with_items:
    - {name: "tis-aliyun-hdfs-plugin.tpi", when: True}
    - {name: "tis-asyncmsg-rocketmq-plugin.tpi", when: True}
    - {name: "tis-hive-flat-table-builder-plugin.tpi", when: True}
    - {name: "tis-k8s-plugin.tpi", when: True}
    - {name: "tis-ds-mysql-plugin.tpi", when: True}
    - {name: "tis-ds-tidb-plugin.tpi", when: True}
    - {name: "tis-kafka-plugin.tpi", when: True}
    - {name: "tis-solr-plugin.tpi", when: True}
   # - {name: "tis-local-dump-build.tpi", when: True}
    - {name: "tis-datax-common-plugin.tpi", when: True}
   # - {name: "{{tis_spark_hive_server_extends_tar_file_name}}", when: need_install_hadoop and need_install_spark}

- name: make soft link for '{{ tis_release_dir }}/{{tis_plugin_release_dir_name}}/{{tis_pkg_version}}'
  file:
    src: "{{ tis_release_dir }}/{{tis_plugin_release_dir_name}}/{{tis_pkg_version}}/{{ item }}"
    dest: "{{ tis_release_dir }}/{{tis_plugin_release_dir_name}}/{{ item }}"
    state: link
  with_lines:
    - find {{ tis_release_dir }}/{{tis_plugin_release_dir_name}}/{{tis_pkg_version}} -type f -name "*" -printf '%f\n'
