{{- if eq .Values.installMode "default" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-appmanager-postrun
  labels:
    name: appmanager-postrun
spec:
  backoffLimit: 1000000
  template:
    metadata:
      name: appmanager-postrun
      labels:
        name: appmanager-postrun
    spec:
      containers:
      - name: job
        image: {{ template "images.postrun" . }}
        imagePullPolicy: {{ .Values.global.images.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ template "name.server-configmap" . }}
      restartPolicy: OnFailure
{{- end -}}
