version: '3'
services:
  atlas:
    build:
      context: .
      dockerfile: Dockerfile.atlas
      args:
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas:latest
    container_name: atlas
    hostname: atlas.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    volumes:
      - ./data:/home/atlas/data
    ports:
      - "21000:21000"
    depends_on:
      atlas-hbase:
        condition: service_started
      atlas-kafka:
        condition: service_started
      atlas-solr:
        condition: service_started
      atlas-zk:
        condition: service_started
    environment:
      - ATLAS_VERSION
    command:
      - /home/atlas/scripts/atlas.sh

  atlas-zk:
    build:
      context: .
      dockerfile: Dockerfile.atlas-zk
    image: atlas-zk
    container_name: atlas-zk
    hostname: atlas-zk.example.com
    networks:
      - atlas
    ports:
      - "2181:2181"

  atlas-solr:
    build:
      context: .
      dockerfile: Dockerfile.atlas-solr
    image: atlas-solr
    container_name: atlas-solr
    hostname: atlas-solr.example.com
    networks:
      - atlas
    ports:
      - "8983:8983"

networks:
  atlas:
    name: atlasnw
