version: '3'
services:
  atlas-build:
    build:
      context: .
      dockerfile: Dockerfile.atlas-build
    image: atlas-build
    container_name: atlas-build
    hostname: atlas-build.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    volumes:
      - ~/.m2:/home/atlas/.m2:delegated
      - ./scripts:/home/atlas/scripts
      - ./patches:/home/atlas/patches
      - ./dist:/home/atlas/dist
      - ./../..:/home/atlas/src:delegated
    depends_on:
      - atlas-base
    environment:
      - ATLAS_VERSION
      - BRANCH
      - BUILD_HOST_SRC
      - GIT_URL
      - PROFILE
      - SKIPTESTS

networks:
  atlas:
    name: atlasnw
