{{- if .Values.saml }}
{{- if .Values.saml.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-saml
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
{{- $root := . }}
    saml.json: '{{ toJson .Values.saml }}'
{{- end -}}
{{- end -}}