---
# tasks file for solr_core
- name: copy solr.tar
  copy:
    src: "{{tis_release_dir}}/{{tis_release_dir_name}}/{{item}}"
    dest: /tmp/
  with_items:
    - "solr.tar.gz"

- name: delete history tar.gz
  file:
    path: /tmp/solr
    state: absent

- name: untar
  unarchive:
    src: /tmp/solr.tar.gz
    dest: /tmp/
    remote_src: yes

- file:
    path: "{{solr_app_dir}}"
    state: directory

- name: synchroniz solr
  synchronize:
    src: /tmp/solr/
    dest: "{{solr_app_dir}}"
    delete: yes
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"
  notify: restart solr

#  - name: create log dir
#    file:
#     path: "{{solr_log_dir}}"
#     state: directory
#     owner: solr

#  - name: copy config.properties
#    template:
#     src: template/hdfs-site-proxy.xml.j2
#     dest: "{{solr_app_dir}}/conf/tis-web-config/hdfs-site.xml"
- name: mkdir tis-web-config
  file:
    path: "{{solr_app_dir}}/conf/tis-web-config"
    state: directory

- name: copy config.properties
  template:
    src: template/{{item}}.j2
    dest: "{{solr_app_dir}}/conf/tis-web-config/{{item}}"
  with_items:
    - "config.properties"
  notify: restart solr

  #  - name: copy solr start script
  #    template:
  #     src: ./template/{{item}}.j2
  #     dest: "{{solr_app_dir}}/{{item}}"
  #    with_items:
  #     - "solr"
  #     - "solr.in.sh"
  #    notify: restart solr

  #  - name: set solr script mode
  #    file:
  #     path: "{{solr_app_dir}}/solr"
  #     mode: '+x'
  #    notify: restart solr

- name: path owner set
  file:
    path: "{{solr_app_dir}}"
    owner: solr
    group: solr
    recurse: yes