# 数据源配置
spring:
  redis:
    database: 1
    host: myBackEndIpAddress
    port: RedisPort
    password: RedisPassword  # 密码（默认为空）
    timeout: 6000ms       # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  datasource:
    hikari:
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 30000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 30000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
    dynamic:
      primary: mysql
      datasource:
        mysql:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://myBackEndIpAddress:mysqlPort/data_cloud?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: RedisPassword

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.datax.service.data.standard.api.entity
  global-config:
    db-config:
      id-type: ASSIGN_ID
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# spring security 配置
security:
  oauth2:
    client:
      access-token-uri: http://myBackEndIpAddress:8612/auth/oauth/token
      user-authorization-uri: http://myBackEndIpAddress:8612/auth/oauth/authorize
      client-id: datax
      client-secret: 123456
      scope: all
    resource:
      loadBalanced: true
      token-info-uri: http://myBackEndIpAddress:8612/auth/oauth/check_token

# Swagger界面内容配置
swagger:
  enable: true
  title: API接口文档
  description: Api Documentation
  version: 1.0.0
  basePackage: cn.datax.service.data.standard.controller
  termsOfServiceUrl: http://www.baidu.com
  contact:
    name: yuwei
    url: http://www.baidu.com
    email: 985134801@qq.com
