{{- if eq .Values.installMode "default" -}}

{{ if .Values.core.init }}

apiVersion: batch/v1
kind: Job
metadata: 
  name: sreworks-core-init-job
  annotations:
spec:
  backoffLimit: 100000
  ttlSecondsAfterFinished: 600
  template:
    spec:
      {{ if .Values.debug }}
      restartPolicy: Never
      {{ else }}
      restartPolicy: OnFailure 
      {{ end }} 
      containers:
      - image: {{ template "images.swcliBuiltinPackage" . }}
        name: job
        command: ["sh"]
        args: ["/app/core.sh"]
        imagePullPolicy: Always
        #args: ["/app/sleep.sh"]
        workingDir: /root
        envFrom:
          - configMapRef:
              name: init-configmap
        volumeMounts:
        - name: run-volume
          mountPath: /app
        - name: swcli-volume
          mountPath: /swcli
 
      volumes:
      - name: run-volume
        configMap:
          name: init-run
      - name: swcli-volume
        configMap:
          name: init-swcli
 {{ end }}
---

{{- $swcliBuiltinPackage := include "images.swcliBuiltinPackage" . -}}

{{ if .Values.saas.init }}

{{ $saasList := .Values.saas.list }}

{{ if .Values.saas.onlyBase }}
{{ $saasList = .Values.saas.baseList }}
{{ end }}

{{ range $saasList }}
apiVersion: batch/v1
kind: Job
metadata: 
  name: sreworks-saas-{{.}}-init-job
  annotations:
spec:
  backoffLimit: 100000
  ttlSecondsAfterFinished: 600
  template:
    spec:
      {{ if $.Values.debug }}
      restartPolicy: Never
      {{ else }}
      restartPolicy: OnFailure 
      {{ end }} 
      containers:
      - image: {{ $swcliBuiltinPackage }}
        name: job
        command: ["sh"]
        #args: ["/app/sleep.sh"]
        imagePullPolicy: Always
        args: ["/app/saas-{{.}}.sh"]
        workingDir: /root
        envFrom:
          - configMapRef:
              name: init-configmap
        volumeMounts:
        - name: run-volume
          mountPath: /app
        - name: swcli-volume
          mountPath: /swcli
 
      volumes:
      - name: run-volume
        configMap:
          name: init-run
      - name: swcli-volume
        configMap:
          name: init-swcli
---
{{ end }}
{{ end }}



{{- end -}}
