apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-opcua-deployment
  name: deviceshifu-opcua-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-opcua-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-opcua-deployment
    spec:
      containers:
      - image: edgehub/deviceshifu-http-opcua:v0.24.0-rc1
        name: deviceshifu-http
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: deviceshifu-config
          mountPath: "/etc/edgedevice/config"
          readOnly: true
        - name: edgedevice-certificate
          mountPath: "/etc/edgedevice/certificate"
          readOnly: true
        env:
        - name: EDGEDEVICE_NAME
          value: "edgedevice-opcua"
        - name: EDGEDEVICE_NAMESPACE
          value: "devices"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: deviceshifu-config
        configMap:
          name: opcua-configmap-0.0.1
      - name: edgedevice-certificate
        configMap:
          name: edgedevice-opcua-certificate
          optional: true
      serviceAccountName: edgedevice-sa
