{{- if eq .Values.installMode "default" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name.server-configmap" . }}
data:
  STORAGE_CLASS: {{ .Values.global.storageClass | default "alicloud-disk-available" | quote }}
  DB_HOST: {{ template "server.database.host" . }}
  DB_PORT: {{ .Values.server.database.port | default "3306" | quote }}
  DB_USER: {{ .Values.server.database.user | quote }}
  DB_PASSWORD: {{ .Values.server.database.password | quote }}
  DB_NAME: {{ .Values.server.database.name | default "appmanager" | quote }}
  APPMANAGER_DB_HOST: {{ template "server.database.host" . }}
  APPMANAGER_DB_PORT: {{ .Values.server.database.port | default "3306" | quote }}
  APPMANAGER_DB_USER: {{ .Values.server.database.user | quote }}
  APPMANAGER_DB_PASSWORD: {{ .Values.server.database.password | quote }}
  APPMANAGER_DB_NAME: {{ .Values.server.database.name | default "appmanager" | quote }}
  APPMANAGER_PACKAGE_DRIVER: {{ .Values.server.package.driver | quote }}
  APPMANAGER_PACKAGE_ENDPOINT: {{ template "server.package.endpoint" . }}
  APPMANAGER_PACKAGE_ENDPOINT_PROTOCOL: {{ .Values.server.package.endpointProtocol| default "http://" | quote }}
  APPMANAGER_PACKAGE_ACCESS_KEY: {{ .Values.server.package.accessKey | quote }}
  APPMANAGER_PACKAGE_SECRET_KEY: {{ .Values.server.package.secretKey | quote }}
  APPMANAGER_PACKAGE_BUCKET_NAME: {{ .Values.server.package.bucketName | default "appmanager" | quote }}
  APPMANAGER_DAG_BUCKET_NAME: {{ .Values.server.dag.bucketName | default "appmanager-dag" | quote }}
  APPMANAGER_REDIS_HOST: {{ template "server.redis.host" . }}
  APPMANAGER_REDIS_PORT: {{ .Values.server.redis.port | default "6379" | quote }}
  APPMANAGER_REDIS_DATABASE: {{ .Values.server.redis.database | default "0" | quote }}
  APPMANAGER_REDIS_PASSWORD: {{ .Values.server.redis.password | quote }}
  APPMANAGER_ENV: {{ .Values.server.env | default "prod" | quote }}
  APPMANAGER_ROCKETMQ_NAMESRV_ENDPOINT: {{ template "server.rocketmq.namesrv" . }}
  APPMANAGER_ACCESS_ID: {{ .Values.server.accessId | quote }}
  APPMANAGER_ACCESS_SECRET: {{ .Values.server.accessSecret | quote }}
  APPMANAGER_CLIENT_ID: {{ .Values.server.clientId | quote }}
  APPMANAGER_CLIENT_SECRET: {{ .Values.server.clientSecret | quote }}
  APPMANAGER_JWT_SECRET_KEY: {{ .Values.server.jwtSecretKey | quote }}
  CLOUD_TYPE: {{ .Values.server.cloudType | default "PaaS" | quote }}
  JVM_XMX: {{ .Values.server.jvmXMX | default "4000m" | quote }}
  DOCKER_HOST: {{ .Values.server.docker.host | default "tcp://127.0.0.1:2375" | quote }}
  DOCKER_REGISTRY: {{ .Values.server.docker.registry | default "reg.docker.alibaba-inc.com" | quote }}
  DOCKER_NAMESPACE: {{ .Values.server.docker.namespace | default "sw" | quote }}
  REMOTE_DOCKER_DAEMON: {{ .Values.server.docker.host | default "tcp://33.27.16.108:2375" | quote }}
  ENDPOINT_PAAS_APPMANAGER: {{ template "name.service" . }}
  ABM_CLUSTER: {{ .Values.server.cluster | default "master" | quote }}
  COOKIE_DOMAIN: {{ template "domain.base" . }}
  NETWORK_PROTOCOL: {{ template "domain.networkProtocol" . }}
  K8S_NAMESPACE: {{ .Release.Namespace | quote }}
  KANIKO_IMAGE: {{ .Values.images.kaniko | default "gcr.io/kaniko-project/executor:latest" | quote }}
  ENABLE_KANIKO: {{ .Values.server.docker.enableKaniko | default "true" | quote }}
  K8S_DOCKER_SECRET: {{ .Values.server.docker.secret | default "server-docker-secret" | quote }}
  APPMANAGER_KAFKA_BROKERS: {{ template "server.kafkaBroker" . }}
  APPMANAGER_KAFKA_DEFAULT_BROKER_PORT: {{ .Values.server.kafkaBrokerPort | quote }}
  APPMANAGER_ENABLE_AUTH: {{ .Values.server.enableAuth | quote }}
  ACCOUNT_SUPER_CLIENT_ID: {{ .Values.gateway.account_super_client_id | quote }}
  ACCOUNT_SUPER_CLIENT_SECRET: {{ .Values.gateway.account_super_client_secret | quote }}
  ACCOUNT_SUPER_ID: {{ .Values.gateway.account_super_id | quote }}
  ACCOUNT_SUPER_SECRET_KEY: {{ .Values.gateway.account_super_secret_key | quote }} 
 
{{- end -}}
