---
# tasks file for console
- name: include install_console_dependencies.yml
  import_tasks: install_console_dependencies.yml

#- name: empty {{tis_data_dir}}/libs/tis-ibatis
#  file:
#    path: "{{tis_data_dir}}/libs/tis-ibatis"
#    state: absent
#
#- name: make empty dir of {{tis_data_dir}}/libs/tis-ibatis
#  file:
#    path: "{{tis_data_dir}}/libs/tis-ibatis"
#    state: directory
#
#- name: install tis-ibatis dependencies
#  unarchive:
#    src: "{{ tis_release_dir }}/{{tis_ibatis_gz_file_name}}"
#    dest: "{{tis_data_dir}}/libs/tis-ibatis/"
#
#- name: clean {{tis_scala_compiler_dependencies_dir_name}}
#  file:
#    path: "{{tis_data_dir}}/libs/{{tis_scala_compiler_dependencies_dir_name}}"
#    state: absent
#
#- name: install {{tis_scala_compiler_dependencies_dir_name}}
#  unarchive:
#    src: "{{ tis_release_dir }}/{{tis_release_dir_name}}/{{tis_scala_compiler_dependencies_gz_file_name}}"
#    dest: "{{tis_data_dir}}/libs/"

- name: git pull {{tis_local_cfg_git_repository}}@master '{{tis_data_dir}}/cfg_repo'
  git:
    repo: '{{tis_local_cfg_git_repository}}'
    dest: '{{tis_data_dir}}/cfg_repo'
    version: 'master'
    force: yes
    accept_hostkey: yes
  when: tis_local_cfg_git_repository_install

- name: init {{tis_data_dir}}/cfg_repo/global
  file:
    path: '{{tis_data_dir}}/cfg_repo/tis_plugin_config/global'
    state: directory
  when: not tis_local_cfg_git_repository_install

- name: copy plugin config file
  template:
    src: "plugin_cfg/{{item.name}}.j2"
    dest: "{{tis_data_dir}}/cfg_repo/tis_plugin_config/{{item.name}}"
    force: no
    mode: '0644'
  when: not tis_local_cfg_git_repository_install and item.when
  with_items:
    - {name: "global/global_config.xml", when: "{{not uber_pkg}}"}
    - {name: "com.qlangtech.tis.offline.FileSystemFactory.xml", when: "{{not uber_pkg}}"}
    - {name: "com.qlangtech.tis.offline.FlatTableBuilder.xml", when: "{{not uber_pkg}}"}
    - {name: "com.qlangtech.tis.offline.IndexBuilderTriggerFactory.xml", when: "{{not uber_pkg}}"}
    - {name: "com.qlangtech.tis.offline.TableDumpFactory.xml", when: "{{not uber_pkg}}"}
    - {name: "com.qlangtech.tis.plugin.incr.IncrStreamFactory.xml", when: "{{not uber_pkg}}"}
    - {name: "com.qlangtech.tis.plugin.k8s.K8sImage.xml", when: True}

- name: "mkdir of com.qlangtech.tis.config.ParamsConfig.xml file"
  file:
    path: "{{tis_data_dir}}/cfg_repo/tis_plugin_config/params-cfg/{{item.pluginDesc}}"
    state: directory
  when: not tis_local_cfg_git_repository_install and item.when
  with_items: "{{params_cfg_types}}"

- name: "copy com.qlangtech.tis.config.ParamsConfig.xml file"
  template:
    src: "plugin_cfg/com.qlangtech.tis.config.ParamsConfig.xml.{{item.pluginDesc}}.j2"
    dest: "{{tis_data_dir}}/cfg_repo/tis_plugin_config/params-cfg/{{item.pluginDesc}}/com.qlangtech.tis.config.ParamsConfig.xml"
    force: no
    mode: '0644'
  when: not tis_local_cfg_git_repository_install and item.when
  with_items: "{{params_cfg_types}}"

- name: copy tar
  copy:
    src: "{{tis_release_dir}}/{{tis_release_dir_name}}/{{item}}"
    dest: /tmp/
  with_items:
    - "tis.tar.gz"

- name: copy plugins from "{{tis_release_dir}}/{{tis_plugin_release_dir_name}}/"
  synchronize:
    src: "{{tis_release_dir}}/{{tis_plugin_release_dir_name}}/"
    dest: "{{tis_data_dir}}/libs/plugins/"
    copy_links: yes
    delete: yes
  when: not uber_pkg
  notify: restart tis-console

- name: "copy plugins from {{tis_release_dir}}/{{tis_plugin_release_dir_name}}/ when in uber_pkg model"
  copy:
    src: "{{tis_release_dir}}/{{tis_plugin_release_dir_name}}/{{item}}.tpi"
    dest: "{{tis_data_dir}}/libs/plugins/"
  when: uber_pkg
  with_items: "{{uber_attach_plugins}}"

- name: delete history tis.tar.gz
  file:
    path: /tmp/tis
    state: absent

- name: untar tis.tar.gz
  unarchive:
    src: /tmp/tis.tar.gz
    dest: /tmp/
    remote_src: yes

- name: "synchroniz tis to {{app_dir}}/{{tis_app_name}}"
  synchronize:
    src: /tmp/tis/
    dest: "{{app_dir}}/{{tis_app_name}}"
    delete: yes
    recursive: yes
  delegate_to: "{{ inventory_hostname }}"
  notify: restart tis-console



#- name: copy config.properties
#  template:
#     src: template/hdfs-site-proxy.xml.j2
#     dest: /opt/app/spring-boot/tis/conf/tis-web-config/hdfs-site.xml

- file:
    path: "{{app_dir}}/{{tis_app_name}}/conf/tis-web-config"
    state: directory

- name: copy config.properties
  template:
    src: "template/{{item}}.j2"
    dest: "{{app_dir}}/{{tis_app_name}}/conf/tis-web-config/{{item}}"
  with_items:
    - "config.properties"
  #   - "yarn-site.xml"
  notify: restart tis-console

- name: path owner set
  file:
    path: '{{app_dir}}/{{tis_app_name}}'
    owner: "{{tis_user}}"
    group: "{{tis_user}}"
    recurse: yes

- name: set tis dir mode
  file:
    path: "{{tis_data_dir}}"
    owner: "{{tis_user}}"
    group: "{{tis_user}}"
    mode: '0777'
    recurse: yes

- name: register file 'system_initialized_token' exist
  shell: 'ls {{ tis_data_dir }}'
  ignore_errors: True
  register: system_initialized_token_exist

- name: " debug system_initialized_token_exist"
  debug:
    var: system_initialized_token_exist

- name: cp file 'tis_console_{{tisconsole_db_type}}.sql'
  copy: src="tis_console_{{tisconsole_db_type}}.sql" dest=/tmp/
  run_once: true
  when: system_initialized_token_exist.stdout.find('system_initialized_token') < 0


# -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=50000
- name: "initialize tis data in dir:{{app_dir}}/{{tis_app_name}} -Ddata.dir={{tis_data_dir}}"
  #shell: java -classpath ../web-start/lib/*:./lib/*:./conf com.qlangtech.tis.runtime.module.action.SysInitializeAction 1>./init_stdout 2>./init_stderr
  shell: java -classpath ../web-start/lib/*:./lib/*:./conf -Ddata.dir={{tis_data_dir}} com.qlangtech.tis.runtime.module.action.SysInitializeAction /tmp/tis_console_{{tisconsole_db_type}}.sql {{tisconsole_db_type}} > init_db.log
  run_once: true
  args:
    chdir: "{{app_dir}}/{{tis_app_name}}"
  when: system_initialized_token_exist.stdout.find('system_initialized_token') < 0

#- fail: msg="Bailing out. this play requires 'bar'"
