apiVersion: v1
appVersion: 0.22.0
description: Thanos is a set of components that can be composed into a highly available metric system with unlimited storage capacity, which can be added seamlessly on top of existing Prometheus deployments.
name: thanos
keywords:
  - thanos
  - prometheus
  - metrics
sources:
  - https://github.com/thanos-io/thanos
  - https://github.com/banzaicloud/banzai-charts/tree/master/thanos
version: 0.22.0
icon: https://raw.githubusercontent.com/thanos-io/thanos/master/website/static/Thanos-logo_full.svg
maintainers:
- name: Banzai Cloud
  email: info@banzaicloud.com
