apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: humidity-detector
  name: humidity-detector
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humidity-detector
  template:
    metadata:
      labels:
        app: humidity-detector
    spec:
      containers:
        - image: humidity-detector:v0.0.1
          name: humidity-detector
          ports:
            - containerPort: 11111
