version: '3'
services:
  atlas-hive:
    build:
      context: .
      dockerfile: Dockerfile.atlas-hive
      args:
        - HIVE_HADOOP_VERSION=${HIVE_HADOOP_VERSION}
        - HIVE_VERSION=${HIVE_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas-hive
    container_name: atlas-hive
    hostname: atlas-hive.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    ports:
      - "10000:10000"
    depends_on:
      atlas-db:
        condition: service_started
      atlas-hadoop:
        condition: service_healthy
      atlas-zk:
        condition: service_started
      atlas-kafka:
        condition: service_started
    environment:
      - HIVE_HADOOP_VERSION
      - HIVE_VERSION
      - ATLAS_VERSION

  atlas-db:
    build:
      context: .
      dockerfile: Dockerfile.atlas-db
    image: atlas-db
    container_name: atlas-db
    hostname: atlas-db.example.com
    networks:
      - atlas

networks:
  atlas:
    name: atlasnw
