version: '3'
services:
  atlas-hadoop:
    build:
      context: .
      dockerfile: Dockerfile.atlas-hadoop
      args:
        - HADOOP_VERSION=${HADOOP_VERSION}
    image: atlas-hadoop
    container_name: atlas-hadoop
    hostname: atlas-hadoop.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    ports:
      - "9000:9000"
      - "8088:8088"
    depends_on:
      - atlas-base
    healthcheck:
      test: "hdfs dfs -ls /"
      interval: 1m30s
      timeout: 10s
      retries: 30
      start_period: 40s
    environment:
      - HADOOP_VERSION

networks:
  atlas:
    name: atlasnw
