version: '3'
services:
  atlas-kafka:
    build:
      context: .
      dockerfile: Dockerfile.atlas-kafka
      args:
        - KAFKA_VERSION=${KAFKA_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas-kafka
    container_name: atlas-kafka
    hostname: atlas-kafka.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    ports:
      - "9092:9092"
    depends_on:
      atlas-zk:
        condition: service_started
    environment:
      - KAFKA_VERSION
      - ATLAS_VERSION

networks:
  atlas:
    name: atlasnw
