version: '3'
services:
  atlas-hbase:
    build:
      context: .
      dockerfile: Dockerfile.atlas-hbase
      args:
        - HBASE_VERSION=${HBASE_VERSION}
        - ATLAS_VERSION=${ATLAS_VERSION}
    image: atlas-hbase
    container_name: atlas-hbase
    hostname: atlas-hbase.example.com
    stdin_open: true
    tty: true
    networks:
      - atlas
    ports:
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    depends_on:
      atlas-hadoop:
        condition: service_healthy
      atlas-zk:
        condition: service_started
      atlas-kafka:
        condition: service_started
    environment:
      - HBASE_VERSION
      - ATLAS_VERSION

networks:
  atlas:
    name: atlasnw
