server:
  port: 5656security.auth.enabled: false

transactionsRateDisplayLimit: 50

kafka:
  topic:
    transactions: livetransactions
    rules: rules
    alerts: alerts
    latency: latency
    current-rules: current-rules
  listeners:
    transactions.id: transactions-listener

  bootstrap-servers: master:9092,node01:9092,node02:9092

web-socket:
  topic:
    transactions: /topic/transactions
    alerts: /topic/alerts
    latency: /topic/latency

management.endpoints.web.exposure.include: mappings, loggers
spring:
  h2.console.enabled: true
  thymeleaf.cache: false
  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  kafka:
    producer:
      bootstrap-servers: master:9092,node01:9092,node02:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer