name: Deployment
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:


jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: '--manifest-path native-io/Cargo.toml --target x86_64-unknown-linux-gnu --release --all-features'
      - uses: actions/upload-artifact@master
        with:
          name: lakesoul-nativeio-x86_64-unknown-linux-gnu
          path: ./native-io/target/x86_64-unknown-linux-gnu/release/liblakesoul_io_c.so

  build-windows-x86_64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: '--manifest-path native-io/Cargo.toml --release --all-features'
      - uses: actions/upload-artifact@master
        with:
          name: lakesoul-nativeio-x86_64-pc-windows-msvc
          path: ./native-io/target/release/lakesoul_io_c.dll

  build-macos-x86_64:
    runs-on: macos-latest
    steps:
      - name: Install automake
        run: brew install automake
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-05-20
          default: true
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./native-io -> target"
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: '--manifest-path native-io/Cargo.toml --release --all-features'
      - uses: actions/upload-artifact@master
        with:
          name: lakesoul-nativeio-x86_64-apple-darwin
          path: ./native-io/target/release/liblakesoul_io_c.dylib

  deploy-maven-package:
    runs-on: ubuntu-latest
    needs: [build-linux-x86_64, build-windows-x86_64, build-macos-x86_64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: lakesoul-nativeio-x86_64-unknown-linux-gnu
          path: ./native-io/target/release/
      - uses: actions/download-artifact@v3
        with:
          name: lakesoul-nativeio-x86_64-apple-darwin
          path: ./native-io/target/release/
      - uses: actions/download-artifact@v3
        with:
          name: lakesoul-nativeio-x86_64-pc-windows-msvc
          path: ./native-io/target/release/
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Release to Maven Central Repository
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
          maven_goals_phases: "deploy"
          maven_args: "-DskipTests -Dmaven.test.skip=true"
          maven_profiles: "cross-build,release-sign-artifacts"
