server:
  port: 9321
spring:
  application:
    name: streamis-server
  mvc:
    servlet:
      path: /api/rest_j/v1
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20303/eureka/
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
