# version: '3'
# services: 
#   buyer:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/buyer-api:4.3.0.1
#     container_name: buyer
#     network_mode: host
#     environment:
#       - TZ=Asia/Shanghai
#       - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC

#   common:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/common-api:4.3.0.1
#     container_name: common
#     environment:
#       - TZ=Asia/Shanghai
#       - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
#     network_mode: host

#   seller:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/seller-api:4.3.0.1
#     container_name: seller
#     environment:
#       - TZ=Asia/Shanghai
#       - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
#     network_mode: host

#   manager:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/manager-api:4.3.0.1
#     container_name: manager
#     environment:
#       - TZ=Asia/Shanghai
#       - JAVA_OPTS=-XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=128m -Xms128m -Xmx256m -Xmn128m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC
#     network_mode: host

#   wap-ui:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/wap-ui:4.3.0.1
#     container_name: wap-ui
#     network_mode: host

#   buyer-ui:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/buyer-ui:4.3.0.1
#     container_name: buyer-ui
#     network_mode: host

#   seller-ui:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/seller-ui:4.3.0.1
#     container_name: seller-ui
#     network_mode: host

#   manager-ui:
#     restart: always
#     image: registry.cn-beijing.aliyuncs.com/lili-images/manager-ui:4.3.0.1
#     container_name: manager-ui
#     network_mode: host

