# permissions for end users to view microservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microservice-viewer-role
rules:
- apiGroups:
  - apps.abm.io
  resources:
  - microservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.abm.io
  resources:
  - microservices/status
  verbs:
  - get
