---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: nodemetrics.slo.koordinator.sh
spec:
  group: slo.koordinator.sh
  names:
    kind: NodeMetric
    listKind: NodeMetricList
    plural: nodemetrics
    singular: nodemetric
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: NodeMetric is the Schema for the nodemetrics API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: NodeMetricSpec defines the desired state of NodeMetric
            properties:
              metricCollectPolicy:
                description: CollectPolicy defines the Metric collection policy
                properties:
                  aggregateDurationSeconds:
                    description: AggregateDurationSeconds represents the aggregation
                      period in seconds
                    format: int64
                    type: integer
                  nodeAggregatePolicy:
                    description: NodeAggregatePolicy represents the target grain of
                      node aggregated usage
                    properties:
                      durations:
                        items:
                          type: string
                        type: array
                    type: object
                  reportIntervalSeconds:
                    description: ReportIntervalSeconds represents the report period
                      in seconds
                    format: int64
                    type: integer
                type: object
            type: object
          status:
            description: NodeMetricStatus defines the observed state of NodeMetric
            properties:
              nodeMetric:
                description: NodeMetric contains the metrics for this node.
                properties:
                  aggregatedNodeUsages:
                    description: AggregatedNodeUsages will report only if there are
                      enough samples
                    items:
                      properties:
                        duration:
                          type: string
                        usage:
                          additionalProperties:
                            properties:
                              devices:
                                items:
                                  properties:
                                    health:
                                      description: Health indicates whether the device
                                        is normal
                                      type: boolean
                                    id:
                                      description: UUID represents the UUID of device
                                      type: string
                                    minor:
                                      description: Minor represents the Minor number
                                        of Device, starting from 0
                                      format: int32
                                      type: integer
                                    resources:
                                      additionalProperties:
                                        anyOf:
                                        - type: integer
                                        - type: string
                                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                        x-kubernetes-int-or-string: true
                                      description: Resources is a set of (resource
                                        name, quantity) pairs
                                      type: object
                                    type:
                                      description: Type represents the type of device
                                      type: string
                                  type: object
                                type: array
                              resources:
                                additionalProperties:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                                description: ResourceList is a set of (resource name,
                                  quantity) pairs.
                                type: object
                            type: object
                          type: object
                      type: object
                    type: array
                  nodeUsage:
                    properties:
                      devices:
                        items:
                          properties:
                            health:
                              description: Health indicates whether the device is
                                normal
                              type: boolean
                            id:
                              description: UUID represents the UUID of device
                              type: string
                            minor:
                              description: Minor represents the Minor number of Device,
                                starting from 0
                              format: int32
                              type: integer
                            resources:
                              additionalProperties:
                                anyOf:
                                - type: integer
                                - type: string
                                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                x-kubernetes-int-or-string: true
                              description: Resources is a set of (resource name, quantity)
                                pairs
                              type: object
                            type:
                              description: Type represents the type of device
                              type: string
                          type: object
                        type: array
                      resources:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: ResourceList is a set of (resource name, quantity)
                          pairs.
                        type: object
                    type: object
                type: object
              podsMetric:
                description: PodsMetric contains the metrics for pods belong to this
                  node.
                items:
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    podUsage:
                      properties:
                        devices:
                          items:
                            properties:
                              health:
                                description: Health indicates whether the device is
                                  normal
                                type: boolean
                              id:
                                description: UUID represents the UUID of device
                                type: string
                              minor:
                                description: Minor represents the Minor number of
                                  Device, starting from 0
                                format: int32
                                type: integer
                              resources:
                                additionalProperties:
                                  anyOf:
                                  - type: integer
                                  - type: string
                                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                  x-kubernetes-int-or-string: true
                                description: Resources is a set of (resource name,
                                  quantity) pairs
                                type: object
                              type:
                                description: Type represents the type of device
                                type: string
                            type: object
                          type: array
                        resources:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          description: ResourceList is a set of (resource name, quantity)
                            pairs.
                          type: object
                      type: object
                  type: object
                type: array
              updateTime:
                description: UpdateTime is the last time this NodeMetric was updated.
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
