#EXAPLE:
#  db-type: "example"
#  name: "example"
#  literal-quote: "'"
#  identifier-quote: "`"
#  driver-class: "com.example.jdbc.Driver" # optional
#  url-prefix: "jdbc:example://" # optional
#  sql-dialect: "datart.data.provider.calcite.dialect.ExampleSqlDialectSupport"  # optional
#  identifier-end-quote: "`"  # optional
#  literal-end-quote: "'"  # optional
#  identifier-escaped-quote: "`"  # optional
#  adapter-class: 'datart.data.provider.jdbc.adapters.ExampleDataProviderAdapter'  # optional
#  quote-identifiers: true  # optional
#  support-sql-limit: true  # optional
#

IMPALA:
  db-type: "impala"
  name: "impala"
  driver-class: "com.cloudera.impala.jdbc41.Driver"
  literal-quote: "'"
  identifier-quote: "`"
  adapter-class: "datart.data.provider.jdbc.adapters.ImpalaDataProviderAdapter"
  url-prefix: "jdbc:impala://"
  sql-dialect: "datart.data.provider.calcite.dialect.ImpalaSqlDialectSupport"


ORACLE:
  quote-identifiers: false

DORIS:
  db-type: "doris"
  name: "doris"
  driver-class: "com.mysql.cj.jdbc.Driver"
  literal-quote: "'"
  identifier-quote: "`"
  adapter-class: "datart.data.provider.jdbc.adapters.DorisDataProviderAdapter"
  url-prefix: "jdbc:mysql://"

STARROCKS:
  db-type: "starrocks"
  name: "starrocks"
  driver-class: "com.mysql.cj.jdbc.Driver"
  literal-quote: "'"
  identifier-quote: "`"
  adapter-class: "datart.data.provider.jdbc.adapters.StarRocksDataProviderAdapter"
  url-prefix: "jdbc:mysql://"


