{{- if .Values.defaultClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.defaultClass.name }}
  annotations:
{{- if .Values.defaultClass.isDefaultClass }}
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: jiva.csi.openebs.io
volumeBindingMode: Immediate
allowVolumeExpansion: {{ .Values.defaultClass.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.defaultClass.reclaimPolicy }}
parameters:
  cas-type: "jiva"
  policy: {{ .Values.defaultPolicy.name }}
{{- end }}
