apiVersion: v1
kind: Service
metadata:
  name: {{ template "harbor.core" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
{{- if  (eq .Values.expose.ingress.controller "gce") }}
  type: NodePort
{{- end }}
  ports:
    - name: {{ ternary "https-web" "http-web" .Values.internalTLS.enabled }}
      port: {{ template "harbor.core.servicePort" . }}
      targetPort: {{ template "harbor.core.containerPort" . }}
{{- if .Values.metrics.enabled}}
    - name: {{ template "harbor.metricsPortName" . }}
      port: {{ .Values.metrics.core.port }}
{{- end }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: core
