apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: shifu-crd-system
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: edgedevices.shifu.edgenesis.io
spec:
  group: shifu.edgenesis.io
  names:
    kind: EdgeDevice
    listKind: EdgeDeviceList
    plural: edgedevices
    singular: edgedevice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EdgeDevice is the Schema for the edgedevices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EdgeDeviceSpec defines the desired state of EdgeDevice
            properties:
              address:
                type: string
              connection:
                description: Connection specifies the EdgeDevice-EdgeNode connection
                  type.
                type: string
              customMetadata:
                additionalProperties:
                  type: string
                type: object
              protocol:
                description: Protocol specifies the EdgeDevice's communication protocol.
                type: string
              protocolSettings:
                description: ProtocolSettings defines protocol settings when connecting
                  to an EdgeDevice
                properties:
                  MQTTSetting:
                    description: MQTTSetting defines MQTT specific settings when connecting
                      to an EdgeDevice
                    properties:
                      MQTTServerAddress:
                        type: string
                      MQTTServerSecret:
                        type: string
                      MQTTTopic:
                        type: string
                    type: object
                  OPCUASetting:
                    description: OPCUASetting defines OPC UA specific settings when
                      connecting to an OPC UA endpoint
                    properties:
                      AuthenticationMode:
                        type: string
                      CertificateFileName:
                        type: string
                      ConfigmapName:
                        type: string
                      ConnectionTimeoutInMilliseconds:
                        format: int64
                        type: integer
                      IssuedToken:
                        type: string
                      OPCUAEndpoint:
                        type: string
                      Password:
                        type: string
                      PrivateKeyFileName:
                        type: string
                      SecurityMode:
                        type: string
                      SecurityPolicy:
                        type: string
                      Username:
                        type: string
                    type: object
                  PLC4XSetting:
                    properties:
                      protocol:
                        type: string
                    type: object
                  SocketSetting:
                    description: SocketSetting defines Socket specific settings when
                      connecting to an EdgeDevice
                    properties:
                      bufferLength:
                        default: 1024
                        format: int64
                        type: integer
                      encoding:
                        default: utf-8
                        type: string
                      networkType:
                        type: string
                    type: object
                  TCPSetting:
                    description: TCPSetting defines TCP forward settings
                    properties:
                      ListenPort:
                        default: "8081"
                        type: string
                      NetworkType:
                        default: tcp
                        type: string
                    type: object
                type: object
              sku:
                description: Sku specifies the EdgeDevice's SKU.
                type: string
            type: object
          status:
            description: EdgeDeviceStatus defines the observed state of EdgeDevice
            properties:
              edgedevicephase:
                description: EdgeDevicePhase is a simple, high-level summary of where
                  the EdgeDevice is in its lifecycle.
                type: string
            type: object
        type: object
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: null
  name: telemetryservices.shifu.edgenesis.io
spec:
  group: shifu.edgenesis.io
  names:
    kind: TelemetryService
    listKind: TelemetryServiceList
    plural: telemetryservices
    singular: telemetryservice
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TelemetryService is the Schema for the telemetryservices API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TelemetryServiceSpec defines the desired state of TelemetryService
            properties:
              customMetadata:
                additionalProperties:
                  type: string
                type: object
              serviceSettings:
                description: ServiceSettings defines service settings on telemetry
                properties:
                  HTTPSetting:
                    description: HTTPSetting defines HTTP specific settings when connecting
                      to an EdgeDevice
                    properties:
                      password:
                        type: string
                      username:
                        type: string
                    type: object
                  MQTTSetting:
                    description: MQTTSetting defines MQTT specific settings when connecting
                      to an EdgeDevice
                    properties:
                      MQTTServerAddress:
                        type: string
                      MQTTServerSecret:
                        type: string
                      MQTTTopic:
                        type: string
                    type: object
                  MinIOSetting:
                    properties:
                      AccessKey:
                        type: string
                      Bucket:
                        type: string
                      FileExtension:
                        type: string
                      RequestTimeoutMS:
                        format: int64
                        type: integer
                      Secret:
                        type: string
                      SecretKey:
                        type: string
                      ServerAddress:
                        type: string
                    type: object
                  SQLSetting:
                    properties:
                      dbName:
                        type: string
                      dbTable:
                        type: string
                      dbtype:
                        type: string
                      secret:
                        type: string
                      serverAddress:
                        type: string
                      username:
                        type: string
                    type: object
                type: object
              telemetrySeriveEndpoint:
                type: string
            type: object
          status:
            description: TelemetryServiceStatus defines the observed state of TelemetryService
            properties:
              telemetryservicephase:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shifu-crd-controller-manager
  namespace: shifu-crd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shifu-crd-leader-election-role
  namespace: shifu-crd-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: shifu-crd-manager-role
rules:
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - edgedevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - edgedevices/finalizers
  verbs:
  - update
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - edgedevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices/finalizers
  verbs:
  - update
- apiGroups:
  - shifu.edgenesis.io
  resources:
  - telemetryservices/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shifu-crd-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shifu-crd-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shifu-crd-leader-election-rolebinding
  namespace: shifu-crd-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shifu-crd-leader-election-role
subjects:
- kind: ServiceAccount
  name: shifu-crd-controller-manager
  namespace: shifu-crd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shifu-crd-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shifu-crd-manager-role
subjects:
- kind: ServiceAccount
  name: shifu-crd-controller-manager
  namespace: shifu-crd-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shifu-crd-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shifu-crd-proxy-role
subjects:
- kind: ServiceAccount
  name: shifu-crd-controller-manager
  namespace: shifu-crd-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: 7ede39d4.edgenesis.io
kind: ConfigMap
metadata:
  name: shifu-crd-manager-config
  namespace: shifu-crd-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: shifu-crd-controller-manager-metrics-service
  namespace: shifu-crd-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: shifu-crd-controller-manager
  namespace: shifu-crd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: bitnami/kube-rbac-proxy:0.14.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --enable-user-metrics
        - --user-metrics-interval=60
        - --source=default
        command:
        - /manager
        image: edgehub/shifu-controller:v0.24.0-rc1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: shifu-crd-controller-manager
      terminationGracePeriodSeconds: 10
